### PR TITLE
Temporarily disable failing test

### PR DESCRIPTION
**Pull request by lptr**
This is to work around https://github.com/gradle/native-platform/issues/262 for now.

### CODE REVIEW

**Review by wolfs — COMMENTED** [review]
Looks good. Could we also disable the test on M1 only?

**Comment by lptr** [comment]
Not sure how to detect M1. Any ideas?

**Comment by wolfs** [comment]
Why are we ignoring the test now for all operating systems and not only for macOS?

**Comment by lptr** [comment]
The test was only enabled for macOS. Now it's not enabled at all.

**Pull request merged**
