### PR TITLE
Add documentation how to test integration with Gradle

### PR DESCRIPTION
**Pull request by wolfs**

### CODE REVIEW

**Comment by lptr** [comment]
Can we put the Gradle-side stuff in permanently, so they wouldn't need mentioning here?

**Comment by wolfs** [comment]
> Can we put the Gradle-side stuff in permanently, so they wouldn't need mentioning here?

What do you mean by the "Gradle-side stuff"? The only which could be done on the Gradle side is to add `mavenLocal()`, and I don't think that is a good idea. Changing the native platform version is necessary dependent on what snapshot/dev build you are using.

**Comment by wolfs** [comment]
@lptr PTAL!

**Comment by lptr** [comment]
NB: it's `--include-build` not `--includeBuild`.

**Comment by wolfs** [comment]
@lptr PTAL!

**Pull request merged**
